### ISSUE TITLE
手势问题

### ISSUE THREAD

**Issue by Licarey** [BmobSnail/SlideNestedPanelLayout#2]
main_top布局放入mapview, 无法手势缩放？？？

**Comment by BmobSnail** [comment]
现在官方出了 BottomSheetDialogFragment，用这个来实现吧，兼容比我的好多了

**Comment by BmobSnail** [comment]
> main_top布局放入mapview, 无法手势缩放？？？
现在官方出了 BottomSheetDialogFragment，用这个来实现吧，兼容比我的好多了
